### ISSUE TITLE
java.lang.NoClassDefFoundError: selogger/logging/Logging

### ISSUE THREAD

**Issue by marcohald** [takashi-ishio/selogger#22]
The Logger Agent works fine on a simple Hello World Programm.
When I run it against another more complex Jar this Error Happens
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: selogger/logging/Logging
        at javafx.beans.property.SimpleBooleanProperty.<clinit>(SimpleBooleanProperty.java:38)
        at com.sun.javafx.application.PlatformImpl.<clinit>(PlatformImpl.java:89)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:337)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
        ... 5 more
```

**Comment by takashi-ishio** [comment]
Thank you for reporting the problem.
I reproduced the problem using a JavaFX-based application (https://github.com/Nurtak/ObjectGraphVisualization):
```
java -javaagent:selogger-0.3.2.jar -jar OGV.jar
```
(The jar file comes from the Java Runnable package on https://github.com/Nurtak/ObjectGraphVisualization/releases)

The error happens probably because the injected code fails to access the logging class for some reason, even though selogger could inject logging code into javafx classes.

A simple work-aorund is excluding javafx classes from logging like this:
```
java -javaagent:selogger-0.3.2.jar=e=javafx -jar OGV.jar
```
In my environment, the JavaFX app successfully launched.

**Comment by takashi-ishio** [comment]
The latest version excludes JavaFX from logging to avoid the problem.  
To enable someone to analyze those removed classes, "i=" option is added.
