### ISSUE TITLE
LogPrinter does not work in Java 8 

### ISSUE THREAD

**Issue by takashi-ishio** [takashi-ishio/selogger#6]
LogPrinter does not work in JDK 8 because it uses a method ByteBuffer.clear() available since Java 9.
```
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
        at selogger.reader.EventReader.load(EventReader.java:76)
        at selogger.reader.EventReader.<init>(EventReader.java:49)
        at selogger.reader.LogPrinter.main(LogPrinter.java:55)
```

**Comment by takashi-ishio** [comment]
Removed Java-9 specific APIs.  
If `mvn package` is executed with Java 8, the code should work.
