### ISSUE TITLE
can not obtain objectType.

### ISSUE THREAD

**Issue by yebityon** [takashi-ishio/selogger#7]
latest version(e81fe80e2334866a7c3149e20bbad33042db3c0d) can not obtain objectType. 

I confirmed that selogger which has the commit ( 27005c644d0a73679baef75fa58be2a5338cfdaa ) can obtain the objectType correctly and has no failed test.

However, seloggers who have after that commit are failed as NPE or can not obtain object type. 

the description is available below.
> $ git log 
commit bb9d8ad98543470efe409abc30db320de5f19d17 (HEAD -> develop)
$ java selogger.reader.LogPrinter > ../../../../experiment/diff_script/binary_search_log.txt 
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "selogger.reader.TypeList.getType(int)" because "this.typeList" is null
        at selogger.reader.ObjectTypeMap.getObjectTypeName(ObjectTypeMap.java:89)
        at selogger.reader.DataIdMap.getObjectType(DataIdMap.java:66)
        at selogger.reader.Event.toString(Event.java:253)
        at selogger.reader.LogPrinter.main(LogPrinter.java:76)

My environment is 
>openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)

Is there a way to get objectType with the latest version?
I will be grateful for any help you can provide.

**Comment by takashi-ishio** [comment]
This was caused by TypeList class.  The format of Types.txt has been updated but the parser was not updated.
